config/routes.rb
Rails.application.routes.draw do
  resources :variant_fields
  resources :properties
  resources :fields
  resources :variants
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/variant_field.rb
class VariantField < ApplicationRecord
  belongs_to :field
  belongs_to :property
  belongs_to :variant
end

app/controllers/variant_fields_controller.rb
class VariantFieldsController < ApplicationController
  before_action :set_variant_field, only: [:show, :edit, :update, :destroy]

  # GET /variant_fields
  # GET /variant_fields.json
  def index
    @variant_fields = VariantField.all
  end

  # GET /variant_fields/1
  # GET /variant_fields/1.json
  def show
  end

  # GET /variant_fields/new
  def new
    @variant_field = VariantField.new
  end

  # GET /variant_fields/1/edit
  def edit
  end

  # POST /variant_fields
  # POST /variant_fields.json
  def create
    @variant_field = VariantField.new(variant_field_params)

    respond_to do |format|
      if @variant_field.save
        format.html { redirect_to @variant_field, notice: 'Variant field was successfully created.' }
        format.json { render :show, status: :created, location: @variant_field }
      else
        format.html { render :new }
        format.json { render json: @variant_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variant_fields/1
  # PATCH/PUT /variant_fields/1.json
  def update
    respond_to do |format|
      if @variant_field.update(variant_field_params)
        format.html { redirect_to @variant_field, notice: 'Variant field was successfully updated.' }
        format.json { render :show, status: :ok, location: @variant_field }
      else
        format.html { render :edit }
        format.json { render json: @variant_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variant_fields/1
  # DELETE /variant_fields/1.json
  def destroy
    @variant_field.destroy
    respond_to do |format|
      format.html { redirect_to variant_fields_url, notice: 'Variant field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variant_field
      @variant_field = VariantField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variant_field_params
      params.require(:variant_field).permit(:name, :belongs_to)
    end
end

app/helpers/variant_fields_helper.rb
module VariantFieldsHelper
end

app/views/variant_fields/_form.html.erb
<%= form_for(variant_field) do |f| %>
  <% if variant_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(variant_field.errors.count, "error") %> prohibited this variant_field from being saved:</h2>

      <ul>
      <% variant_field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :belongs_to %>
    <%= f.text_field :belongs_to %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variant_fields/edit.html.erb
<h1>Editing Variant Field</h1>

<%= render 'form', variant_field: @variant_field %>

<%= link_to 'Show', @variant_field %> |
<%= link_to 'Back', variant_fields_path %>

app/views/variant_fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variant Fields</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Belongs to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variant_fields.each do |variant_field| %>
      <tr>
        <td><%= variant_field.name %></td>
        <td><%= variant_field.belongs_to %></td>
        <td><%= link_to 'Show', variant_field %></td>
        <td><%= link_to 'Edit', edit_variant_field_path(variant_field) %></td>
        <td><%= link_to 'Destroy', variant_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variant Field', new_variant_field_path %>

app/views/variant_fields/new.html.erb
<h1>New Variant Field</h1>

<%= render 'form', variant_field: @variant_field %>

<%= link_to 'Back', variant_fields_path %>

app/views/variant_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @variant_field.name %>
</p>

<p>
  <strong>Belongs to:</strong>
  <%= @variant_field.belongs_to %>
</p>

<%= link_to 'Edit', edit_variant_field_path(@variant_field) %> |
<%= link_to 'Back', variant_fields_path %>